'use strict'
// This file is automatically generated and does not need to be modified
// 本文件自动生成，不需要修改
import adminBreadcrumb from '../components/admin-breadcrumb'
import adminHeader from '../components/admin-header'
import adminSidebar from '../components/admin-sidebar'
const version = '0.0.11'

export {
  version,
  adminBreadcrumb,
  adminHeader,
  adminSidebar
}
